### ISSUE TITLE
报错反馈

### ISSUE THREAD

**Issue by WKhistory** [WKhistory/DBDAuto_BPWeb#1]

**Comment by Amutona** [comment]
大佬，2.0版本的节省模式用不了，卡在页面乱点。（而且点不中技能）

**Comment by WKhistory** [comment]
你可以看到血网背景是具有透明度的，这个问题是因为颜色判断被背景场景干扰。
高配/技能优先模式受干扰较小，你可以先使用此模式，我正在尝试修复这个问题。
