### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by YunnrEX** [WKhistory/DBDAuto_BPWeb#3]
大佬，这个自动点学网的脚本，普通模式下，手电筒的透镜类附加品（如聚焦镜，宽阔透镜等），全部不能识别，需要自己手动点，并且选择节约或者技能的话，有时候会一直选中可分享技能的那三个（不是学网的，不能点），导致无法继续进行，有没有什么解决办法

**Comment by WKhistory** [comment]
我要先确定你是否关闭了滤镜。
